[application]

# App (Project) Name
name = "firelog"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "firelog"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = false

# which files or dirs will be watcher monitoring
watch_path = []

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["/main.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
